= Quarkus Solace

include::./includes/attributes.adoc[]

== Introduction

The https://solace.com/products/platform/[Solace PubSub+ Platform]'s https://solace.com/products/event-broker/software/[software event broker] efficiently streams event-driven information between applications, IoT devices and user interfaces running in the cloud, on-premises, and hybrid environments using open APIs and protocols like AMQP, JMS, MQTT, REST and WebSocket. It can be installed into a variety of public and private clouds, PaaS, and on-premises environments, and brokers in multiple locations can be linked together in an https://solace.com/what-is-an-event-mesh/[event mesh] to dynamically share events across the distributed enterprise.

== Quarkus Extension for Solace

Solace Quarkus Extension provides the ability to integrate with Solace PubSub+ message brokers. The events published by this extension to solace will be available on event mesh and in the same way the extension can subscribe to any event available on event mesh.

Users have the choice to use the extension in two ways

{empty}1. `com.solace.quarkus:quarkus-solace-client`

This extension provides only Solace Java Messaging API and users need to have their own implementation and configuration to interact with Solace PubSub+ broker.

If you want to use this extension, you need to add the `com.solace.quarkus:quarkus-solace-client` extension first to your build file.

For instance, with Maven, add the following dependency to your POM file:

[source,xml,subs=attributes+]
----
<dependency>
    <groupId>com.solace.quarkus</groupId>
    <artifactId>quarkus-solace-client</artifactId>
    <version>3.0.0</version>
</dependency>
----

{empty}2. `com.solace.quarkus:quarkus-solace-messaging-connector`

This extension is based on reactive messaging framework and provides pre-defined configurations for incoming and outgoing channels.

If you want to use this extension, you need to add the `com.solace.quarkus:quarkus-solace-messaging-connector` extension first to your build file.

For instance, with Maven, add the following dependency to your POM file:

[source,xml,subs=attributes+]
----
<dependency>
    <groupId>com.solace.quarkus</groupId>
    <artifactId>quarkus-solace-messaging-connector</artifactId>
    <version>3.0.0</version>
</dependency>
----

NOTE: Solace Quarkus Extension 3.1.0 is based on Quarkus 3.15.x with Java 17 as baseline.

[[extension-configuration-reference]]
== Extension Configuration Reference

include::includes/quarkus-solace.adoc[leveloffset=+1, opts=optional]

[[extension-incoming-configuration-reference]]
== Incoming Configuration Reference

include::includes/quarkus-solace-extension-incoming.adoc[leveloffset=+1, opts=optional]

[[extension-outgoing-configuration-reference]]
== Outgoing Configuration Reference

include::includes/quarkus-solace-extension-outgoing.adoc[leveloffset=+1, opts=optional]

[[extension-common-configuration-reference]]
== Common Configuration Reference

include::includes/quarkus-solace-extension-common.adoc[leveloffset=+1, opts=optional]

[[configuring-quarkus-solace-client]]
== Configuring Quarkus Solace Client

Solace Broker supports different ways to connect and authenticate users. This section shows how to pass <<quarkus-solace_quarkus.solace-extra, extra properties>> to quarkus solace client in different scenarios. Please refer to https://docs.solace.com/API-Developer-Online-Ref-Documentation/pubsubplus-java/constant-values.html#com.solace.messaging.config.SolaceProperties[Solace Properties] for supported properties and definitions.

{empty}1. Connecting to a standalone broker with basic authentication
[source,yaml]
----
quarkus.solace.host=tcp://localhost:55555
quarkus.solace.vpn=default
quarkus.solace.authentication.basic.username=test
quarkus.solace.authentication.basic.password=test
----

{empty}2. Connecting to a standalone broker with TLS and basic authentication. This assumes you have a publicly signed CA.
[source,yaml]
----
quarkus.solace.host=tcps://localhost:55443
quarkus.solace.vpn=default
quarkus.solace.authentication.basic.username=test
quarkus.solace.authentication.basic.password=test
----

{empty}3. Connecting to a standalone broker with TLS, basic authentication and custom trust store which hold your CA.
[source,yaml]
----
quarkus.solace.host=tcps://localhost:55443
quarkus.solace.vpn=default
quarkus.solace.authentication.basic.username=test
quarkus.solace.authentication.basic.password=test
quarkus.solace.tls.trust-store-path=
quarkus.solace.tls.trust-store-type=
quarkus.solace.tls.trust-store-password=
----

{empty}4. Connecting to a standalone broker with TLS, trust store and client certificate authentication. In case of client certificate authentication broker will read from configured username source(ex: Common Name, Subject Alt Name etc...). Refer to https://docs.solace.com/Security/Configuring-Client-Authentication.htm#Client-Cert[Solace Client Certificate Authentication].
[source,yaml]
----
quarkus.solace.host=tcps://localhost:55443
quarkus.solace.vpn=default
quarkus.solace.authentication.scheme=AUTHENTICATION_SCHEME_CLIENT_CERTIFICATE
quarkus.solace.tls.trust-store-path=
quarkus.solace.tls.trust-store-type=
quarkus.solace.tls.trust-store-password=
quarkus.solace.authentication.client-cert.keystore=
quarkus.solace.authentication.client-cert.keystore-password=
quarkus.solace.authentication.client-cert.keystore-format=
----

{empty}5. Connecting to a standalone broker with OAUTH authentication scheme.
[source,yaml]
----
quarkus.solace.host=tcp://localhost:55555
quarkus.solace.vpn=default
quarkus.solace.authentication.scheme=AUTHENTICATION_SCHEME_OAUTH2
quarkus.solace.oidc.client-name=solace // client name provided in oidc client config below
quarkus.solace.oidc.refresh.interval=50s // Refresh interval should be less than access token expiry time. Otherwise extension will fail to update access token in solace session.
quarkus.solace.oidc.refresh.timeout=10s // Token Refresh API timeout. Default is set to 10 seconds.

quarkus.oidc-client.solace.auth-server-url=http://localhost:7777/auth/realms/master
quarkus.oidc-client.solace.client-id=<client-id>
quarkus.oidc-client.solace.credentials.secret=<client-secret>
# 'client' is a shortcut for `client_credentials`
quarkus.oidc-client.solace.grant.type=client
----

{empty}6. Connecting to a standalone broker with TLS and OAUTH authentication scheme.
[source,yaml]
----
quarkus.solace.host=tcps://localhost:55443
quarkus.solace.vpn=default
quarkus.solace.authentication.scheme=AUTHENTICATION_SCHEME_OAUTH2
quarkus.solace.tls.trust-store-path=
quarkus.solace.tls.trust-store-type=
quarkus.solace.tls.trust-store-password=
quarkus.solace.oidc.client-name=solace // client name provided in oidc client config below
quarkus.solace.oidc.refresh.interval=50s // Refresh interval should be less than access token expiry time. Otherwise extension will fail to update access token in solace session.
quarkus.solace.oidc.refresh.timeout=10s // Token Refresh API timeout. Default is set to 10 seconds.

quarkus.oidc-client.solace.auth-server-url=http://localhost:7777/auth/realms/master
quarkus.oidc-client.solace.client-id=<client-id>
quarkus.oidc-client.solace.credentials.secret=<client-secret>
# 'client' is a shortcut for `client_credentials`
quarkus.oidc-client.solace.grant.type=client
quarkus.oidc-client.solace.tls.trust-store-file=<path-to-truststore-file>
quarkus.oidc-client.solace.tls.key-store-password=
quarkus.oidc-client.solace.tls.verification=<enable-or-disable-tls-verification>
----

For more details on Quarkus OIDC client supported configuration please refer to https://quarkus.io/guides/security-openid-connect-client-reference[OPENID CONNECT (OIDC) AND OAUTH2 CLIENT AND FILTERS] and https://quarkus.io/guides/security-oidc-configuration-properties-reference[OIDC configuration reference]

NOTE: The current version is tested with client_credentials grant type where Solace broker is configured as Resource Server.

{empty}7. Connecting to a HA broker. Here you can configure both active and standby URL and the client will switch connectivity based on availability. Remaining configurations and authentication mechanisms can be used as-is.
[source,yaml]
----
quarkus.solace.host=tcp://active-host-name:55555,tcp://standby-host-name:55555
quarkus.solace.vpn=default
quarkus.solace.authentication.basic.username=test
quarkus.solace.authentication.basic.password=test
----

In similar way other authentication mechanisms can be enabled


[[configuring-quarkus-solace-messaging-connector]]
== Configuring Quarkus Solace Messaging Connector

Reactive Messaging framework supports different messaging backends it employs a generic vocabulary:

* Applications send and receive messages. A message wraps a payload and can be extended with some metadata. With the Solace connector, a message corresponds to Inbound or Outbound Message.

* Messages transit on channels. Application components connect to channels to publish and consume messages. The Solace connector maps channels to Solace queues and topics.

* Channels are connected to message backends using connectors. Connectors are configured to map incoming messages to a specific channel (consumed by the application) and collect outgoing messages sent to a specific channel. Each connector is dedicated to a specific messaging technology. For example, the connector dealing with Solace is named `quarkus-solace`.

The extension supports two types of messaging client `direct` and `persistent`. By default `persistent` client is enabled.

A minimal configuration for the Solace connector with an incoming channel and `persistent` client looks like the following:

The following lines of configuration assumes that a exclusive queue is already provisioned on the broker
[source,properties]
----
quarkus.solace.host=tcp://localhost:55555
quarkus.solace.vpn=default
quarkus.solace.authentication.basic.username=basic
quarkus.solace.authentication.basic.password=basic

mp.messaging.incoming.temperatures.connector=quarkus-solace
mp.messaging.incoming.temperatures.consumer.queue.name=temperatures
----

The extension also supports provisioning queues and subscriptions on broker given that the user has role access to create queues with subscriptions. Configuration is as follows

[source,properties]
----
quarkus.solace.host=tcp://localhost:55555
quarkus.solace.vpn=default
quarkus.solace.authentication.basic.username=basic
quarkus.solace.authentication.basic.password=basic

mp.messaging.incoming.temperatures.connector=quarkus-solace
mp.messaging.incoming.temperatures.consumer.queue.missing-resource-creation-strategy=create-on-start
mp.messaging.incoming.temperatures.consumer.queue.add-additional-subscriptions=true
mp.messaging.incoming.temperatures.consumer.subscriptions=hello/foobar
----

A minimal configuration for the Solace connector with an incoming channel and `direct` client looks like the following:

[source,properties]
----
quarkus.solace.host=tcp://localhost:55555
quarkus.solace.vpn=default
quarkus.solace.authentication.basic.username=basic
quarkus.solace.authentication.basic.password=basic

mp.messaging.incoming.temperatures.client.type=direct
mp.messaging.incoming.temperatures.connector=quarkus-solace
mp.messaging.incoming.temperatures.consumer.subscriptions=sensor/temperatures
----

1. When running in dev mode or tests dev services will automatically start a Solace PubSub+ broker and if broker configuration details are not provided the extension automatically picks up the details of broker started by dev services.

2. If `consumer.queue.name` property is not specified, channel name will be used as queue name.

[[receiving-messages-from-solace]]
== Receiving messages from Solace

Using the previous configuration, Quarkus application can receive message in several possible ways.

__Direct Payload__
[source,java]
----
import org.eclipse.microprofile.reactive.messaging.Incoming;
import jakarta.enterprise.context.ApplicationScoped;
@ApplicationScoped
public class TemperaturesConsumer {
    @Incoming("temperatures")
    public void consume(byte[] temperature) {
        // process.
    }
}
----

__Message__
[source,java]
----
@ApplicationScoped
public class TemperaturesConsumer {
    @Incoming("temperatures")
    public CompletionStage<Void> consume(Message<byte[]> msg) {
        // access record metadata
        SolaceInboundMetadata metadata = msg.getMetadata(SolaceInboundMetadata.class).orElseThrow();
        // process the message payload.
        double temperature = Double.parseDouble(new String(p.getPayload()));
        // Acknowledge the incoming message
        return msg.ack();
    }
}
----

__SolaceInboundMessage__ This is a wrapper to incoming Inbound Message from Solace Messaging API

[source,java]
----
import com.solace.messaging.receiver.InboundMessage;
@ApplicationScoped
public class TemperaturesConsumer {
    @Incoming("temperatures")
    public void consume(InboundMessage inboundMessage) {
        // process the message payload.
        String temperature = inboundMessage.getPayloadAsString();
    }
}
----

[[acknowledgement-handling]]
== Acknowledgment Handling

By default, for `persistent` client acknowledgement strategy is set to client acknowledgement. This gives greater control over acknowledgement and ensures that messages are acknowledged only after successful processing.

In case of `direct` client no acknowledgement is sent to the broker.

[source,java]
----
@ApplicationScoped
public class TemperaturesConsumer {
    @Incoming("temperatures")
    public CompletionStage<Void> consume(Message<byte[]> msg) {
        // access record metadata
        SolaceInboundMetadata metadata = msg.getMetadata(SolaceInboundMetadata.class).orElseThrow();
        // process the message payload.
        double temperature = Double.parseDouble(new String(p.getPayload()));
        // Acknowledge the incoming message
        return msg.ack();
    }
}
----

[[failure-strategies]]
== Failure Strategies

If a message is nacked, a failure strategy is applied. Refer to <<extension-incoming-configuration-reference>><<quarkus-solace_quarkus.consumer.failure-strategy>>. The default strategy is set to `ignore` and move on to next message. Following are the strategies supported by Quarkus Solace Messaging Connector extension.

`ignore` - Mark the message as IGNORED, will continue processing with next message. It TTL and DMQ are configured on the queue message will be moved to DMQ once TTL is reached. If no DMQ is configured but TTL is set message will be lost.

`fail` - Mark the message as FAILED, broker will redeliver the message. Nacks are supported on event brokers 10.2.1 and later, so enable this strategy based on broker version.

`discard` - Mark the message as REJECTED, broker will discard the message. The message will be moved to DMQ if DMQ is configured for queue and DMQ Eligible is set on message otherwise message will be lost. Nacks are supported on event brokers 10.2.1 and later, so enable this strategy based on broker version.

`error_topic` - Will publish the message to configured error topic, on success the message will be acknowledged in the queue.

[[sending-messages-to-solace]]
== Sending messages to Solace

Outgoing channel configuration to publish `persistent` messages to Solace.

[source,properties]
----
quarkus.solace.host=tcp://localhost:55555
quarkus.solace.vpn=default
quarkus.solace.authentication.basic.username=basic
quarkus.solace.authentication.basic.password=basic

mp.messaging.outgoing.temperatures-out.connector=quarkus-solace
mp.messaging.outgoing.temperatures-out.producer.topic=temperatures
----

Outgoing channel configuration to publish `direct` messages to Solace.

[source,properties]
----
quarkus.solace.host=tcp://localhost:55555
quarkus.solace.vpn=default
quarkus.solace.authentication.basic.username=basic
quarkus.solace.authentication.basic.password=basic

mp.messaging.outgoing.temperatures-out.client.type=direct
mp.messaging.outgoing.temperatures-out.connector=quarkus-solace
mp.messaging.outgoing.temperatures-out.producer.topic=temperatures
----

1. When running in dev mode or tests dev services will automatically start a Solace PubSub+ broker and if broker configuration details are not provided the extension automatically picks up the details of broker started by dev services.

2. If `producer.topic` property is not specified, channel name will be used as topic name.

Using the previous configuration Quarkus application can publish messages as follows

[source,java]
----
import io.smallrye.mutiny.Multi;
import org.eclipse.microprofile.reactive.messaging.Outgoing;

import jakarta.enterprise.context.ApplicationScoped;
import java.time.Duration;
import java.util.Random;

@ApplicationScoped
public class TemperaturesProducer {

    private final Random random = new Random();

    @Outgoing("temperatures-out")
    public Multi<Double> generate() {
        // Emit 1000 records
        return Multi.createFrom().range(0, 1000)
            .map(x -> random.nextDouble());
    }

}
----

You can also generate a `org.eclipse.microprofile.reactive.messaging.Message` with required metadata and publish to Solace.

[source,java]
----
@ApplicationScoped
public class TemperaturesProducer {
    private final Random random = new Random();

    @Outgoing("temperatures-out")
    Multi<Message<Double>> publishTemperatures() {
        return Multi.createFrom().range(0, 1000)
            .map(i -> {
                 SolaceOutboundMetadata outboundMetadata = SolaceOutboundMetadata.builder()
                .setApplicationMessageId(Integer.toString(i)).createPubSubOutboundMetadata();
                 return Message.of(random.nextDouble(), Metadata.of(outboundMetadata));
            });
    }
}
----

*SolaceOutboundMetadata* allows to configure metadata for the message. It supports all the headers supported by Solace and custom user properties. In addition to this it also supports configuring dynamic topic which overrides the default topic in application configuration file.

Generating `org.eclipse.microprofile.reactive.messaging.Message` with dynamic topic and publish to Solace.

[source,java]
----
@ApplicationScoped
public class TemperaturesProducer {
    private final Random random = new Random();

    @Outgoing("temperatures-out")
    Multi<Message<Double>> publishTemperatures() {
        return Multi.createFrom().range(0, 1000)
            .map(i -> {
                 SolaceOutboundMetadata outboundMetadata = SolaceOutboundMetadata.builder()
                .setApplicationMessageId(Integer.toString(i))
                .setDynamicDestination("device/" + Integer.toString(i) + "/temperature").createPubSubOutboundMetadata();
                 return Message.of(random.nextDouble(), Metadata.of(outboundMetadata));
            });
    }
}
----

Generating `org.eclipse.microprofile.reactive.messaging.Message` with partition key and publish to Solace.

[source,java]
----
@ApplicationScoped
public class TemperaturesProducer {
    private final Random random = new Random();

    @Outgoing("temperatures-out")
    Multi<Message<Double>> publishTemperatures() {
        return Multi.createFrom().range(0, 1000)
            .map(i -> {
                String partitionKey = "Group-1";
                if(i % 2 == 0) {
                    partitionKey = "Group-2";
                }
                 SolaceOutboundMetadata outboundMetadata = SolaceOutboundMetadata.builder()
                .setApplicationMessageId(Integer.toString(i))
                .setPartitionKey(partitionKey).createPubSubOutboundMetadata();
                 return Message.of(random.nextDouble(), Metadata.of(outboundMetadata));
            });
    }
}
----

Sending messages with __@Emitter__

[source,java]
----
@Path("/temperatures")
public class PublisherResource {

    @Channel("temperatures-out")
    MutinyEmitter<Temperature> temperatureEmitter;

    @POST
    @Path("/publish")
    public Uni<Void> publish(Temperature temperature) {
        return temperatureEmitter.send(temperature);
    }
}
----

== Producer Acknowledgement

Producer can return successful acknowledgement when <<quarkus-solace_quarkus.producer.waitForPublishReceipt>> is enabled.

This property is considered only when <<quarkus-solace_quarkus.client.type>> is set to `persistent`. The connector will wait for response from broker and will return success or failed acknowledgement.

In case of <<quarkus-solace_quarkus.client.type>> is set to `direct` this property is ignored as broker will not send any response. By default, success acknowledgement is returned and any failures during publish are logged as exceptions.

== Producer Back-Pressure strategies

Quarkus Solace Messaging connector provides three different strategies to handle back-pressure when publishing messages

{empty}1.Reject - Publisher will start rejecting messages once specified limit is reached

{empty}2.Wait - Publisher is throttled when a specified limit is reached

{empty}3.Elastic - Use an unlimited internal buffer (default)

CAUTION: In the current version we don't recommend to use back-pressure strategy `Reject` as it is in evolving phase.

Refer to <<extension-outgoing-configuration-reference>><<quarkus-solace_quarkus.producer.back-pressure.strategy>> and <<extension-outgoing-configuration-reference>><<quarkus-solace_quarkus.producer.back-pressure.buffer-capacity>> on how to configure back-pressure for producer.

[[processing-messages]]
== Processing Messages

Applications streaming data often need to consume some events from a topic, process them and publish the result to a different topic. A processor method can be simply implemented using both the *@Incoming* and *@Outgoing* annotations:

[source,java]
----
import org.eclipse.microprofile.reactive.messaging.Incoming;
import org.eclipse.microprofile.reactive.messaging.Outgoing;

import jakarta.enterprise.context.ApplicationScoped;

@ApplicationScoped
public class TemperaturesProcessor {

    @Incoming("temperatures-in")
    @Outgoing("temperatures-out")
    public double process(byte[] temperature) {
        return (Double.parseDouble(new String(p.getPayload())) - 32) * 5 / 9;
    }

}
----

[[open-telemetry-tracing]]
== Open Telemetry Tracing

Extension supports generating trace messages for th messages consumed and published by the extension. To enabling tracing for consumers and producers use the below configuration.
[source,yaml]
----
quarkus.solace.host=tcp://localhost:55555
quarkus.solace.vpn=default
quarkus.solace.authentication.basic.username=test
quarkus.solace.authentication.basic.password=test

mp.messaging.incoming.temperatures.connector=quarkus-solace
mp.messaging.incoming.temperatures.consumer.queue.name=temperatures
mp.messaging.incoming.temperatures.client.tracing-enabled=true

mp.messaging.outgoing.temperatures-out.connector=quarkus-solace
mp.messaging.outgoing.temperatures-out.producer.topic=temperatures
mp.messaging.outgoing.temperatures-out.client.tracing-enabled=true
----

NOTE: Context Propagation is not fully supported in current version.

[[health-checks]]
== Health Checks

Quarkus provides several health checks for Solace. These checks are used in combination with the *quarkus-smallrye-health* extension.

=== Reactive Messaging Health Checks

When using Reactive Messaging and the Quarkus Solace Messaging Connector, each configured channel (incoming or outgoing) provides startup, liveness and readiness checks.

The startup check verifies that the communication with Solace Broker is established.

The liveness check captures any unrecoverable failure happening during the communication with Solace.

The readiness check verifies that the Quarkus Solace Messaging Connector is ready to consume/produce messages to the configured Solace queues/topics.

[[dev-services]]
== Dev Services

Solace Dev Services for Quarkus will spin up latest version of Solace PubSub standard with label `solace` when running tests or in dev mode. Solace Dev Services are enabled by default and will check for any existing containers with same label to reuse. If none is present a new container is started.

[[metrics]]
== Metrics

Quarkus Solace Messaging Connector exposes different metrics provided by Solace Java Messaging API. The metrics are enabled by default and can be accessed at `http://localhost:8080/q/dev-ui/io.quarkus.quarkus-micrometer/prometheus`

