version: 3
project:
  locator: SolaceProducts_quarkus-solace-jcsmp-client
  id: SolaceProducts_quarkus-solace-jcsmp-client
  name: quarkus-solace-jcsmp-client
  teams: []
  labels:
    - java
vendoredDependencies:
  forceRescans: false
  scanMethod: CLILicenseScan
  licenseScanPathFilters:
    exclude:
      - "./.git"
      - "./.github"
paths:
  exclude:
    - ./.git
    - ./.github
telemetry:
  scope: full
